language: ruby
install: "bin/wad"
before_install: npm install -g harp
script: make deploy
deploy:
  provider: s3
  access_key_id:
    secure: HdO0qPeh0J1jHDxky746Hd0Qxmaif/kqnaBR4qSLHiFcK/HlRgrpScPfKR19tVsadR8aHaFeq2Qrfr7JBMzBsKevxYB9y3YP7SCQ+/53EGs+lc5asWJt6hB94QhWSTnbsz//1xifvaJh30BCjxw5f/SGVzMY7WUYonOfkUy8RfA=
  secret_access_key:
    secure: aFf6SNc9vQvCv3500vMihpoAkvDO3qbh05f2pqY7LKoqdJPztH1f+FOqewAbgVLMkNRzhFk77hZHbeQ9+XsL/4BAP+SCeT39J+vR9MM8hvq47YapUqgoyVbyEPtsYxHs7r60QWvhnz1uk4ILeHNrQ3SXL9U4K1uLhxjeS8QTE6o=
  bucket: gee.io
  skip_cleanup: true
  local-dir: www
  on:
    tags: true
env:
  global:
    secure: ZJC4UhHFRTZ7/XRM6gsZ75G/+uF4MNE/olffMoeNGcobBNAucJ9XqQZ6loYmAaEh/qbFTr1YKaDqUuUy4DlBOzU3ou7j4rKqzLwBpFNIg6lvrCF2D1Hc6RvjFG8CqZlgSzUY1teycs+Fnl7cn/mmfH7lM5xQeEgvk0Oqn97Qnyo=
    - S3_BUCKET_NAME=bundler-cache-gee.io
    - S3_REGION=us-east-1
